//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokingTest.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmokingTest.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[Table_1](
        ///	[Row_Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[Rowguid] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [nvarchar](50) NOT NULL,
        ///	[StrValue2] [nvarchar](50) NULL,
        ///	[IntValue] [int] NOT NULL,
        ///	[IntValue2] [int] NULL,
        ///	[Money] [money] NOT NULL,
        ///	[Money2] [money] NULL,
        ///	[Time_Stamp] [timestamp] NULL,
        ///	[SeqGuid] [uniqueidentifier] NOT NULL,
        ///	[SeqGuid2] [uniqueidentifier] NULL,
        ///	[StrValue3] [nvarchar](50) NOT NULL,
        /// CONSTRAINT [PK_Table_1_1] PRIMARY KEY CLUSTERED (	[Row_Id] ASC ) 
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CreateTable1Script {
            get {
                return ResourceManager.GetString("CreateTable1Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE [MyNorthwind]
        ///GO
        ///
        ///****** Object:  Table [dbo].[TestAncillaryDelete]    Script Date: 06/03/2013 15:55:41 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///SET ANSI_PADDING ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[TestAncillaryDelete](
        ///	[GuidId] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[DecValue] [money] NULL,
        ///	[IntId] [int] NULL,
        ///	[TimeStampValue] [timestamp] NOT NULL,
        /// CONSTRAINT [PK_TestAncillaryDelete] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidId] ASC
        ///)WITH (PAD_INDEX  = OF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestAncillaryDeleteScript {
            get {
                return ResourceManager.GetString("TestAncillaryDeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE [MyNorthwind]
        ///GO
        ///
        ///****** Object:  Table [dbo].[TestAncillaryUpdate]    Script Date: 06/03/2013 11:55:18 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///SET ANSI_PADDING ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[TestAncillaryUpdate](
        ///	[GuidId] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[DecValue] [money] NULL,
        ///	[IntId] [int] NULL,
        ///	[TimeStampValue] [timestamp] NOT NULL,
        /// CONSTRAINT [PK_TestAncillaryUpdate] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidId] ASC
        ///)WITH (PAD_INDEX  = OF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestAncillaryUpdateScript {
            get {
                return ResourceManager.GetString("TestAncillaryUpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///CREATE TABLE [dbo].[TestConcurrencyException](
        ///	[GuiId] [uniqueidentifier] NOT NULL,
        ///	[TstValue] [timestamp] NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[IntValue] [int] NULL,
        /// CONSTRAINT [PK_TestConcurrencyException] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuiId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///
        ///GO
        ///if exists (select * from sysobjects where id = object_id(N&apos;[GetTestConcurrencyExce [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestConcurrencyExceptionScript {
            get {
                return ResourceManager.GetString("TestConcurrencyExceptionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///CREATE TABLE [dbo].[TestConcurrencytDelete](
        ///	[GuidRow] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[TimeStampValue] [timestamp] NULL,
        ///	[BinaryValue] [binary](50) NULL,
        /// CONSTRAINT [PK_TestConcurrencytDelete] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidRow] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY] 的本地化字符串。
        /// </summary>
        internal static string TestConcurrencytDeleteScript {
            get {
                return ResourceManager.GetString("TestConcurrencytDeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[TestConcurrencyUpdate](
        ///	[GuidRow] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[TimeStampValue] [timestamp] NULL,
        ///	[BinaryValue] [binary](50) NULL,
        /// CONSTRAINT [PK_TestConcurrencyUpdate] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidRow] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY] 的本地化字符串。
        /// </summary>
        internal static string TestConcurrencyUpdateScript {
            get {
                return ResourceManager.GetString("TestConcurrencyUpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///CREATE TABLE [dbo].[TestCUDValueTypeZero](
        ///	[Id] [int] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[ByteValue] [binary](50) NULL,
        ///	[IntValue] [int] NULL,
        /// CONSTRAINT [PK_TestCUDValueTypeZero] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)
        ///) 
        ///
        ///
        ///
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string TestCUDValueTypeZeroScript {
            get {
                return ResourceManager.GetString("TestCUDValueTypeZeroScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///CREATE TABLE [dbo].[TestDelete](
        ///	[Id] [int] NOT NULL,
        ///	[Guiid] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[TstValue] [timestamp] NULL,
        /// CONSTRAINT [PK_TestDelete] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC,
        ///	[Guiid] ASC
        ///))
        /// 的本地化字符串。
        /// </summary>
        internal static string TestDeleteScript {
            get {
                return ResourceManager.GetString("TestDeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[TestInsert](
        ///	[Ids] [int] IDENTITY(1,1) NOT NULL,
        ///	[PkId] [int] NOT NULL,
        ///	[TimeStampValue] [timestamp] NULL,
        ///	[GuidId] [uniqueidentifier] NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[ByteValue] [varbinary](50) NULL,
        /// CONSTRAINT [PK_TestInsert] PRIMARY KEY CLUSTERED 
        ///(
        ///	[PkId] ASC
        ///))
        ///GO
        ///
        ///ALTER TABLE [dbo].[TestInsert] ADD  CONSTRAINT [DF_TestInsert_GuidId]  DEFAULT (newsequentialid()) FOR [GuidId]
        ///GO
        /// 的本地化字符串。
        /// </summary>
        internal static string TestInsertScript {
            get {
                return ResourceManager.GetString("TestInsertScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[TestNotNullDataTypeTable](
        ///	[a] [bigint] NOT NULL,
        ///	[b] [binary](50) NOT NULL,
        ///	[c] [bit] NOT NULL,
        ///	[d] [char](10) NOT NULL,
        ///	[e] [date] NOT NULL,
        ///	[f] [datetime] NOT NULL,
        ///	[g] [decimal](18, 4) NOT NULL,
        ///	[h] [float] NOT NULL,
        ///	[i] [image] NOT NULL,
        ///	[j] [int] NOT NULL,
        ///	[k] [money] NOT NULL,
        ///	[l] [nchar](10) NOT NULL,
        ///	[m] [ntext] NOT NULL,
        ///	[n] [numeric](18, 4) NOT NULL,
        ///	[o] [nvarchar](50) NOT NULL,
        ///	[p] [nvarchar](max) NOT NULL,
        ///	[q] [real] NOT NULL,
        ///	[r] [smallda [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestNotNullDataTypeScript {
            get {
                return ResourceManager.GetString("TestNotNullDataTypeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///CREATE TABLE [dbo].[TestPK](
        ///	[Id] [int] NOT NULL,
        ///	[Guiid] [uniqueidentifier] NOT NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[TstValue] [timestamp] NULL,
        /// CONSTRAINT [PK_TestPK] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC,
        ///	[Guiid] ASC
        ///))
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string TestPKScript {
            get {
                return ResourceManager.GetString("TestPKScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///CREATE TABLE [dbo].[TestSPOut](
        ///	[GuiId] [uniqueidentifier] NOT NULL,
        ///	[TstValue] [timestamp] NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[IntValue] [int] NULL,
        /// CONSTRAINT [PK_TestSPOut] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuiId] ASC
        ///)
        ///) 
        ///
        ///GO
        ///
        ///IF   exists (select * from sysobjects where id = object_id(N&apos;[TestSPOut]&apos;) and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)  
        ///DROP PROC [dbo].TestSPOut
        ///GO
        ///CREATE PROC GetToSingleTestSPOut(
        ///	@GuiId uniqueidentifier,
        ///	@StrValue varchar(50) output
        ///)
        ///AS
        ///DECLARE  @Str [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestSPOutScript {
            get {
                return ResourceManager.GetString("TestSPOutScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///CREATE TABLE [dbo].[TestSqlSplice](
        ///	[GuidId] [uniqueidentifier] NOT NULL,
        ///	[IntValue] [int] NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[TimeStampValue] [timestamp] NULL,
        /// CONSTRAINT [PK_TestSqlSplice] PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidId] ASC
        ///))
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string TestSqlSpliceScript {
            get {
                return ResourceManager.GetString("TestSqlSpliceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[TestSqlTrace](
        ///	[TextData] [ntext] NULL,
        ///	[BinaryData] [image] NULL,
        ///	[TransactionID] [bigint] NULL,
        ///	[NTUserName] [nvarchar](256) NULL,
        ///	[StartTime] [datetime] NULL,
        ///	[SqlText] [nvarchar](max) NULL,
        ///	[id] [int] IDENTITY(1,1) NOT NULL,
        ///	[DatabaseID] [int] NOT NULL,
        ///PRIMARY KEY CLUSTERED 
        ///(
        ///	[id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
        /// 的本地化字符串。
        /// </summary>
        internal static string TestSqlTraceScript {
            get {
                return ResourceManager.GetString("TestSqlTraceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///CREATE TABLE [dbo].[TestTimeStamp](
        ///	[GuidId] [uniqueidentifier] NOT NULL,
        ///	[TsValue] [timestamp] NOT NULL,
        ///	[StrValue] [varchar](50) NOT NULL,
        ///	[IntValue] [int] NOT NULL,
        ///PRIMARY KEY CLUSTERED 
        ///(
        ///	[GuidId] ASC
        ///))
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string TestTimeStampScript {
            get {
                return ResourceManager.GetString("TestTimeStampScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [dbo].[TestUpdate](
        ///	[Ids] [int] IDENTITY(1,1) NOT NULL,
        ///	[PkId] [int] NOT NULL,
        ///	[TimeStampValue] [timestamp] NULL,
        ///	[GuidId] [uniqueidentifier] NULL,
        ///	[StrValue] [varchar](50) NULL,
        ///	[ByteValue] [binary](50) NULL,
        /// CONSTRAINT [PK_TestUpdate] PRIMARY KEY CLUSTERED 
        ///(
        ///	[PkId] ASC
        ///))
        ///GO
        ///
        ///
        ///ALTER TABLE [dbo].[TestUpdate] ADD  CONSTRAINT [DF_TestUpdate_GuidId]  DEFAULT (newsequentialid()) FOR [GuidId]
        ///GO
        /// 的本地化字符串。
        /// </summary>
        internal static string TestUpdateScript {
            get {
                return ResourceManager.GetString("TestUpdateScript", resourceCulture);
            }
        }
    }
}
